### ISSUE TITLE
How should I launch the tool?

### ISSUE THREAD

**Issue by JIE-sakura** [D3Ext/WEF#45]
When using the WEF command, I can't seem to find it.

**Comment by CyVenom** [comment]
1. Try Running out which network interface you are using by running the following command in your terminal  **nmcli device status**  or **ip link show**  
2.  Look for the interface that has an IP address and is listed as **"UP."**
3. then run   **wef -i wlan0**  this might be different because ur interface might be different  Example : wlan0, wlan1,eth0 ,eth1,
4. Example If ur interface is **eth0** then run **wef -i eth0**
